import Head from "next/head";
import MainLayout from "./layout";
import Logo from "../../public/photos/logo.png";

export default function Home() {
  const logoImage = Logo.src;
  return (
    <>
      <Head>
        <title>KUKeight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./photos/logo.png" />
      </Head>
      <MainLayout>
        <div className="text-nowrap title">
          <img className="logo-img" src={logoImage} width="130" height="130" />
          <div className="full-title d-inline">
            <div className="d-inline title-one">UKeight</div>&nbsp;&nbsp;
            <div className="title-two d-inline">Studio</div>
          </div>
        </div>
      </MainLayout>
    </>
  );
}
